/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author moniq
 */
public class Tela2 extends javax.swing.JFrame {

    /**
     * Creates new form Tela2
     */
    public Tela2() {
        initComponents();
        setSize(1062, 626);
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        certa2 = new javax.swing.JButton();
        errada21 = new javax.swing.JButton();
        errada2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("OS VÍDEOS DA FSOCIETY SÃO BASEADOS NO GRUPO HACKER");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 70, 790, 60);

        certa2.setBackground(new java.awt.Color(0, 255, 102));
        certa2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        certa2.setText("ANONYMOUS");
        certa2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                certa2MouseClicked(evt);
            }
        });
        certa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                certa2ActionPerformed(evt);
            }
        });
        getContentPane().add(certa2);
        certa2.setBounds(30, 330, 220, 60);

        errada21.setBackground(new java.awt.Color(153, 153, 153));
        errada21.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        errada21.setText("CARBANAK");
        getContentPane().add(errada21);
        errada21.setBounds(30, 400, 220, 60);

        errada2.setBackground(new java.awt.Color(153, 153, 153));
        errada2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        errada2.setText("LAZARUS");
        getContentPane().add(errada2);
        errada2.setBounds(30, 260, 220, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/tela de perguntas.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1026, 634);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void certa2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_certa2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_certa2MouseClicked

    private void certa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_certa2ActionPerformed
        dispose();
                new Tela3().setVisible(true);
    }//GEN-LAST:event_certa2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela3().setVisible(true);
            }
        });
    
        
        
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton certa2;
    private javax.swing.JButton errada2;
    private javax.swing.JButton errada21;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
